# Impostazioni base del sito
title: Nome del Progetto di Ricerca
description: Una breve descrizione del tuo progetto di ricerca.
baseurl: "" # importante se il tuo sito non è all'indirizzo root
url: "https://coenv-project.github.io" # sostituisci con il tuo username

# Impostazioni del tema
theme: minima # o qualsiasi altro tema Jekyll che stai usando

# Metadati dell'autore/sito
author:
  name: Nome del Coordinatore del Progetto
  email: email@esempio.com

# Sezioni del Progetto di Ricerca
research_units:
  - name: Unità di Ricerca 1
    description: Descrizione della Unità di Ricerca 1.
  - name: Unità di Ricerca 2
    description: Descrizione della Unità di Ricerca 2.
  - name: Unità di Ricerca 3
    description: Descrizione della Unità di Ricerca 3.

# Principal Investigators
principal_investigators:
  - name: Nome Investigatore 1
    photo: /path/to/photo1.jpg
  - name: Nome Investigatore 2
    photo: /path/to/photo2.jpg
  - name: Nome Investigatore 3
    photo: /path/to/photo3.jpg

# Pubblicazioni
publications:
  - title: "Titolo della Pubblicazione 1"
    link: http://linkalla pubblicazione1.com
  - title: "Titolo della Pubblicazione 2"
    link: http://linkalla pubblicazione2.com
  - title: "Titolo della Pubblicazione 3"
    link: http://linkalla pubblicazione3.com

# Escludi file dal sito
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
  - .jekyll-metadata

# Plugin (se necessario)
plugins:
  - jekyll-feed
